Fixed the problem with pw (plane wave) dos (density of states) generation. The problem was with inconsistent binaries. I recompiled QE (quantum espresso) for Ubuntu 9.04 and replaced the binaries pw.x and dos.x (ovini/bin/). Make sure that in the suture they point to the right QE binaries instead of using them from ovini source code.
Fixed problem with error:
RuntimeError:  matplotlib.use() must be called *before* pylab
or matplotlib.backends is imported for the first time.

You need to conevert strings to float before you plot image with matplotlib! (E.g. "5.007" -> 5.007)

git-svn-id: svn://danse.us/AbInitio@217 4efde5e4-ebd3-4001-8375-eeb568285340